### ISSUE TITLE
Running the --help option throws an exception

### ISSUE THREAD

**Issue by RileyLRoberts** [fluentverification/stamina#13]
I just ran Stamina with only --help and an exception is thrown. Message below:

Exception in thread "main" java.lang.NullPointerException
	at stamina.StaminaCL.exit(StaminaCL.java:455)
	at stamina.StaminaCL.parseArguments(StaminaCL.java:378)
	at stamina.StaminaCL.doParsing(StaminaCL.java:275)
	at stamina.StaminaCL.run(StaminaCL.java:107)
	at stamina.StaminaCL.main(StaminaCL.java:94)

**Comment by RileyLRoberts** [comment]
Fixed this. Added a check to see if the model was null before clearing it. Only clear model if it isn't null.
